# See: https://github.com/drone/drone/blob/v0.4.0/docs/build/README.md

compose:
  cache:
    image: redis
build:
  tests:
    image: mediafactory/video-transcoding-api
    environment:
      - GOROOT=/usr/local/go
      - GOPATH=/drone
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/drone/bin:/usr/local/go/bin
    commands:
      - make testdeps test
    when:
      branch: master
      event: push
  deploy:
    image: mediafactory/video-transcoding-api
    environment:
      - GOROOT=/usr/local/go
      - GOPATH=/drone
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/drone/bin:/usr/local/go/bin
      - INFRA_REPO=$$NP_INFRA_REPO
      - NP_PATH=$$NP_PATH_VALUE
      - NP_REPO=$$NP_REPO
      - PACKER_VPC_ID=$$NP_PACKER_VPC_ID
      - PACKER_SUBNET_ID=$$NP_PACKER_SUBNET_ID
      - S3_VARS_BUCKET=$$NP_S3_VARS_BUCKET
      - S3_STATE_BUCKET=$$NP_S3_STATE_BUCKET
      - AWS_DEFAULT_REGION=$$NP_AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID=$$NP_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$$NP_AWS_SECRET_ACCESS_KEY
      - GITHUB_TOKEN=$$NP_GITHUB_TOKEN
      - ASG_TOPIC=$$NP_ASG_TOPIC
    commands:
      - git clone --depth=1 https://$GITHUB_TOKEN@github.com/$INFRA_REPO.git $NP_PATH
      - go get github.com/${NP_REPO}
      - np build transcoding-api:dev#$${COMMIT:0:7}
      - np deploy transcoding-api:dev#$${COMMIT:0:7}
      - aws autoscaling put-notification-configuration --auto-scaling-group-name transcoding-api-dev-$${COMMIT:0:7}-web --topic-arn ${ASG_TOPIC} --notification-types "autoscaling:EC2_INSTANCE_LAUNCH" "autoscaling:EC2_INSTANCE_LAUNCH_ERROR"
      - np deploy transcoding-api:stg#$${COMMIT:0:7}
      - aws autoscaling put-notification-configuration --auto-scaling-group-name transcoding-api-stg-$${COMMIT:0:7}-web --topic-arn ${ASG_TOPIC} --notification-types "autoscaling:EC2_INSTANCE_LAUNCH" "autoscaling:EC2_INSTANCE_LAUNCH_ERROR"
    when:
      branch: master
      event: push
  make_live:
    image: mediafactory/video-transcoding-api
    environment:
      - GOROOT=/usr/local/go
      - GOPATH=/drone
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/drone/bin:/usr/local/go/bin
      - INFRA_REPO=$$NP_INFRA_REPO
      - NP_PATH=$$NP_PATH_VALUE
      - NP_REPO=$$NP_REPO
      - PACKER_VPC_ID=$$NP_PACKER_VPC_ID
      - PACKER_SUBNET_ID=$$NP_PACKER_SUBNET_ID
      - S3_VARS_BUCKET=$$NP_S3_VARS_BUCKET
      - S3_STATE_BUCKET=$$NP_S3_STATE_BUCKET
      - AWS_DEFAULT_REGION=$$NP_AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID=$$NP_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$$NP_AWS_SECRET_ACCESS_KEY
      - GITHUB_TOKEN=$$NP_GITHUB_TOKEN
      - ASG_TOPIC=$$NP_ASG_TOPIC
    commands:
      - git clone --depth=1 https://$GITHUB_TOKEN@github.com/$INFRA_REPO.git $NP_PATH
      - go get github.com/${NP_REPO}
      - np deploy transcoding-api:prd#$${COMMIT:0:7}
      - aws autoscaling put-notification-configuration --auto-scaling-group-name transcoding-api-prd-$${COMMIT:0:7}-web --topic-arn ${ASG_TOPIC} --notification-types "autoscaling:EC2_INSTANCE_LAUNCH" "autoscaling:EC2_INSTANCE_LAUNCH_ERROR"
    when:
      event: tag
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: $$SLACK_USERNAME
    channel: $$SLACK_CHANNEL
    when:
      branch: master
      event: push
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: $$SLACK_USERNAME
    channel: $$SLACK_CHANNEL
    when:
      event: tag
  downstream_dev_stg:
    image: plugins/drone-downstream
    server: $$INTERNAL_DRONE_ENDPOINT
    token: $$DRONE_TOKEN
    repositories:
      - $$INTEGRATION_TESTS_REPO@dev
      - $$INTEGRATION_TESTS_REPO@stg
    fork: true
    when:
      branch: master
  downstream_prd:
    image: plugins/drone-downstream
    server: $$INTERNAL_DRONE_ENDPOINT
    token: $$DRONE_TOKEN
    repositories:
      - $$INTEGRATION_TESTS_REPO@prd
    fork: true
    when:
      event: tag
