package service

import (
	"github.com/nytm/video-transcoding-api/db"
)

// swagger:parameters newPreset
type newPresetParams struct {
	// id of the preset. This is an optional parameter, it will be
	// automatically generated by the API when not defined.
	//
	// in:body
	ID string `json:"presetId"`

	// the mapping of the provider name to the id of the preset in the
	// provider.
	//
	// in: body
	// required: true
	ProviderMapping map[string]string `json:"providerMapping"`
}

func (p *newPresetParams) Preset() db.Preset {
	return db.Preset{ID: p.ID, ProviderMapping: p.ProviderMapping}
}
