// generate_readme generates the README file based on the swagger output.
package main

import (
	"encoding/json"
	"flag"
	"log"
	"os"
	"strings"
	"text/template"
)

var readmeTemplate = template.Must(template.New("README.md").Parse(`<!--
This file is automatically generated from Swagger documentation, please do not
edit it.
-->

#{{.Info.Title}}

{{.Info.Description}}
`))

var (
	inputFileName  string
	outputFileName string
)

var replaces = map[string]string{
	"h2:": "##",
	"b:":  "-",
}

func init() {
	flag.StringVar(&inputFileName, "i", "swagger.json", "Swagger file to use as input")
	flag.StringVar(&outputFileName, "o", "README.md", "Name of the destination file")
	flag.Parse()
}

type swaggerData struct {
	Info struct {
		Title       string
		Description string
	}
}

func main() {
	inputFile, err := os.Open(inputFileName)
	if err != nil {
		log.Fatal(err)
	}
	defer inputFile.Close()

	outputFile, err := os.Create(outputFileName)
	if err != nil {
		log.Fatal(err)
	}
	defer outputFile.Close()

	var data swaggerData
	err = json.NewDecoder(inputFile).Decode(&data)
	if err != nil {
		log.Fatalf("Failed to load input file: %s", err)
	}

	for k, v := range replaces {
		data.Info.Description = strings.Replace(data.Info.Description, k, v, -1)
	}

	err = readmeTemplate.Execute(outputFile, data)
	if err != nil {
		log.Fatalf("Failed to write output file: %s", err)
	}
}
