// generate_readme generates the README file based on the swagger output.
package main

import (
	"encoding/json"
	"flag"
	"log"
	"os"
	"text/template"
)

var readmeTemplate = template.Must(template.New("README.md").Parse(`<!--
This file is automatically generated from Swagger documentation, please do not
edit it.
-->

#video-transcoding-api

{{.info.description}}
`))

var (
	inputFileName  string
	outputFileName string
)

func init() {
	flag.StringVar(&inputFileName, "i", "swagger.json", "Swagger file to use as input")
	flag.StringVar(&outputFileName, "o", "README.md", "Name of the destination file")
	flag.Parse()
}

func main() {
	inputFile, err := os.Open(inputFileName)
	if err != nil {
		log.Fatal(err)
	}
	defer inputFile.Close()

	outputFile, err := os.Create(outputFileName)
	if err != nil {
		log.Fatal(err)
	}
	defer outputFile.Close()

	var data map[string]interface{}
	err = json.NewDecoder(inputFile).Decode(&data)
	if err != nil {
		log.Fatalf("Failed to load input file: %s", err)
	}

	err = readmeTemplate.Execute(outputFile, data)
	if err != nil {
		log.Fatalf("Failed to write output file: %s", err)
	}
}
