package db

// Job represents the job that is persisted in the repository of the Transcoding
// API.
//
// swagger:model
type Job struct {
	// id of the job. It's automatically generated by the API when creating
	// a new Job.
	//
	// unique: true
	ID string `redis-hash:"-" json:"jobId"`

	// name of the provider
	//
	// required: true
	ProviderName string `redis-hash:"providerName" json:"providerName"`

	// id of the job on the provider
	//
	// required: true
	ProviderJobID string `redis-hash:"providerJobID" json:"providerJobId"`

	// boolean flag that denotes an adaptive streaming job.
	// Defaults to false.
	//
	// required: false
	AdaptiveStreaming bool `redis-hash:"adaptiveStreaming" json:"adaptiveStreaming"`
}

// Preset represents the preset that is persisted in the repository of the
// Transcoding API
//
// Each preset is just an aggregator of provider presets, where each preset in
// the API maps to a preset on each provider
//
// swagger:model
type Preset struct {
	// name of the preset
	//
	// unique: true
	// required: true
	Name string `redis-hash:"-" json:"name"`

	// mapping of provider name to provider's internal preset id.
	//
	// required: true
	ProviderMapping map[string]string `redis-hash:",expand" json:"providerMapping"`
}
